language: python
os: linux
dist: xenial
python:
- '2.7'
- '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tree
install:
- pip install pytz boto3
script:
- export BUILD_ID="$TRAVIS_BUILD_ID"
- "./runtests.sh"
