language: python
python:
  - '2.7'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree
  - mkdir -p "${HOME}"/minio/bin
  - mkdir -p "${HOME}"/minio/data
  - mkdir -p "${HOME}"/minio/data/miniobucket
  - wget -nc -O "${HOME}"/minio/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
  - chmod +x "${HOME}"/minio/bin/minio
install:
  - pip install -r requirements.txt
script:
  - export MINIO_ACCESS_KEY=minio
  - export MINIO_SECRET_KEY=miniostorage
  - export S3_ACCESS_KEY=minio
  - export S3_SECRET_KEY=miniostorage
  - export S4CMD_OPTS="--endpoint-url=http://127.0.0.1:9000"
  - export USE_MINIO_SERVER=true
  - "${HOME}/minio/bin/minio server ${HOME}/minio/data &>${HOME}/minio/data/server.log &"
  - export REMOTEDIR=s3://miniobucket
  - "./runtests.sh"
