language: python
python:
- '2.7'
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y tree
- mkdir -p "${HOME}"/minio/bin
- mkdir -p "${HOME}"/minio/data
- wget -nc -O "${HOME}"/minio/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio
- chmod +x "${HOME}"/minio/bin/minio
install:
- pip install -r requirements.txt
script:
# Export environment variables for s4cmd
- export S3_SECRET_KEY=aEmMY45evpLAMMhV3GO0c2dI6PfrCqmKEeUuezVJ
- export S3_ACCESS_KEY=RMG3GO0ANSES38NN2IKS
- export S4CMD_OPTS="--endpoint-url=http://127.0.0.1:9000"
# Run minio server in background
- "${HOME}"/minio/bin/minio server "${HOME}"/minio/data &
- "./runtests.sh"
- killall minio
